name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-bash:
    name: Shellcheck (bash)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update -y && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          shopt -s globstar
          shellcheck -x install.sh menu.sh restore.sh scripts/**/*.sh || true

  lint-yaml:
  name: Lint YAML
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: |
          docker-compose.yml
          .github/workflows
        config_file: .yamllint

  build-admin:
    name: Build admin image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t freenetvpn-admin ./admin

  validate-compose:
    name: Validate docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install docker compose
        run: sudo apt-get update -y && sudo apt-get install -y docker-compose
      - name: Config check
        run: docker-compose config
